# Generated by Django 4.1 on 2022-08-25 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_category_listing_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='isActive',
            new_name='is_active',
        ),
    ]
