# Generated by Django 4.1 on 2022-08-27 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_listing_price_listing_bid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='bid',
            new_name='price',
        ),
    ]
