# Generated by Django 4.1 on 2022-08-30 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_rename_author_comments_writer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='writer',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='bid',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
