# Generated by Django 4.1 on 2022-08-30 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_rename_writer_comments_author_alter_bid_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='author',
            new_name='writer',
        ),
    ]
