# Generated by Django 4.1 on 2022-08-31 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_alter_comments_listing_alter_comments_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='text',
            field=models.CharField(max_length=500),
        ),
    ]
